In [50]:
import numpy as np

with open('sample_input.txt') as f:
    data = np.array([[int(y) for y in list(x)] for x in f.read().split('\n')])
print(data)

[[0 0 1 0 0]
 [1 1 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 0 1 0 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [1 1 0 0 1]
 [0 0 0 1 0]
 [0 1 0 1 0]]


In [51]:
most_arr = (np.average(data, axis=0) > 0.5).astype(int)
most = ""
least_arr = (np.average(data, axis=0) < 0.5).astype(int)
least = ""

for i in range(most_arr.size):
    most += str(most_arr[i])
    least += str(least_arr[i])
gamma = int(most, 2)
epsilon = int(least, 2)
print(gamma * epsilon)

198


In [68]:
o2_arr = data.copy()
co2_arr = data.copy()
o2_valid = np.ones(o2_arr.shape[0]).astype(bool)
co2_valid = o2_valid.copy()

ind = 0

while(o2_arr.shape[0] > 1 or co2_arr.shape[0] > 1):
    #o2:
    if o2_arr.shape[0] > 1:
        most_o2 = np.sum(o2_arr, axis=0)
        if 2*most_o2[ind] < o2_arr.shape[0]:
            most_o2 = 0
        else:
            most_o2 = 1
        o2_arr = o2_arr[np.where(most_o2 == o2_arr[:, ind])]
        print(o2_arr)
    #co2
    if co2_arr.shape[0] > 1:
        most_co2 = np.sum(co2_arr, axis=0)
        if 2*most_co2[ind] >= co2_arr.shape[0]:
            most_co2 = 0
        else:
            most_co2 = 1
        co2_arr = co2_arr[np.where(most_co2 == co2_arr[:, ind])]
    ind += 1
o2 = 0
co2 = 0
for i in range(o2_arr.size):
    o2 += str(o2_arr[i])
    co2 += str(co2_arr[i])
o2 = int(o2,)

[[1 1 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 0 1 0 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [1 1 0 0 1]]
[[1 0 1 1 0]
 [1 0 1 1 1]
 [1 0 1 0 1]
 [1 0 0 0 0]]
[[1 0 1 1 0]
 [1 0 1 1 1]
 [1 0 1 0 1]]
[[1 0 1 1 0]
 [1 0 1 1 1]]
[[1 0 1 1 1]]


(12, 5)