In [36]:
from collections import deque
import numpy as np
import re
with open('input.txt') as f:
    data = np.array([list(x) for x in f.read().split('\n')], dtype=np.int64)
data

array([[1, 2, 2, 4, 3, 4, 6, 3, 8, 4],
       [5, 6, 2, 1, 1, 2, 8, 5, 8, 7],
       [6, 3, 8, 8, 4, 2, 6, 5, 4, 6],
       [1, 5, 5, 6, 2, 4, 7, 7, 5, 6],
       [1, 4, 5, 1, 8, 1, 1, 5, 7, 3],
       [1, 8, 3, 2, 3, 8, 8, 1, 2, 2],
       [2, 7, 4, 8, 5, 4, 5, 6, 4, 7],
       [2, 5, 8, 2, 8, 7, 7, 4, 3, 2],
       [3, 1, 8, 5, 6, 4, 3, 8, 7, 1],
       [2, 2, 2, 4, 8, 7, 6, 6, 2, 7]], dtype=int64)

In [35]:
steps = 100
pt1 = data.copy()
flashes = 0

def increment_neighbors(arr, x, y):
    x1 = max(x - 1, 0); y1 = max(y - 1, 0)
    x2 = min(x + 1, arr.shape[0]) + 1
    y2 = min(y + 1, arr.shape[0]) + 1
    arr[x1:x2, y1:y2] += 1
    arr[x, y] = int(-1e15)
    return arr
            
for n in range(steps):
    pt1 = pt1 + 1
    while (pt1 > 9).any():
        x, y = np.argwhere(pt1 > 9)[0]
        pt1 = increment_neighbors(pt1, x, y)
        flashes += 1
    pt1[pt1 < 0] = 0
    print(pt1, flashes)
print(flashes)


[[6 5 9 4 2 5 4 3 3 4]
 [3 8 5 6 9 6 5 8 2 2]
 [6 3 7 5 6 6 7 2 8 4]
 [7 2 5 2 4 4 7 2 5 7]
 [7 4 6 8 4 9 6 5 8 9]
 [5 2 7 8 6 3 5 7 5 6]
 [3 2 8 7 9 5 2 8 3 2]
 [7 9 9 3 9 9 2 2 4 5]
 [5 9 5 7 9 5 9 6 6 5]
 [6 3 9 4 8 6 2 6 3 7]] 0
[[8 8 0 7 4 7 6 5 5 5]
 [5 0 8 9 0 8 7 0 5 4]
 [8 5 9 7 8 8 9 6 0 8]
 [8 4 8 5 7 6 9 6 0 0]
 [8 7 0 0 9 0 8 8 0 0]
 [6 6 0 0 0 8 8 9 8 9]
 [6 8 0 0 0 0 5 9 4 3]
 [0 0 0 0 0 0 7 4 5 6]
 [9 0 0 0 0 0 0 8 7 6]
 [8 7 0 0 0 0 6 8 4 8]] 35
[[0 0 5 0 9 0 0 8 6 6]
 [8 5 0 0 8 0 0 5 7 5]
 [9 9 0 0 0 0 0 0 3 9]
 [9 7 0 0 0 0 0 0 4 1]
 [9 9 3 5 0 8 0 0 6 3]
 [7 7 1 2 3 0 0 0 0 0]
 [7 9 1 1 2 5 0 0 0 9]
 [2 2 1 1 1 3 0 0 0 0]
 [0 4 2 1 1 2 5 0 0 0]
 [0 0 2 1 1 1 9 0 0 0]] 80
[[2 2 6 3 0 3 1 9 7 7]
 [0 9 2 3 0 3 1 6 9 7]
 [0 0 3 2 2 2 1 1 5 0]
 [0 0 4 1 1 1 1 1 6 3]
 [0 0 7 6 1 9 1 1 7 4]
 [0 0 5 3 4 1 1 1 2 2]
 [0 0 4 2 3 6 1 1 2 0]
 [5 5 3 2 2 4 1 1 2 2]
 [1 5 3 2 2 4 7 2 1 1]
 [1 1 3 2 2 3 0 2 1 1]] 96
[[4 4 8 4 1 4 4 0 0 0]
 [2 0 4 4 1 4 4 0 0 0]
 [2 2 5 3 3 3 3 4 9

0 8
