In [50]:
import numpy as np
with open('input.txt') as f:
    data = [x.split(' -> ') for x in f.read().split('\n')]
data = np.array([[list(map(int, y.split(','))) for y in x] for x in data])
#data


In [28]:
# part one:
grid = np.zeros((np.max(data[:,:,0])+1, np.max(data[:,:,1])+1))
for v in range(data.shape[0]):
    #horizontal:
    if data[v, 0, 0] == data[v, 1, 0]:
        start = data[v, 0, 1]
        end = data[v, 1, 1]
        x = data[v, 0, 0]
        if end < start:
            start, end = end, start
        for y in range(start, end+1):
            grid[x, y] += 1
    #vertical:
    if data[v, 0, 1] == data[v, 1, 1]:
        start = data[v, 0, 0]
        end = data[v, 1, 0]
        if end < start:
            start, end = end, start
        y = data[v, 0, 1]
        for x in range(start, end+1):
            grid[x, y] += 1
print(grid.T)
print(np.sum(grid>1))

5373


In [51]:
#part2
grid = np.zeros((np.max(data[:,:,0])+1, np.max(data[:,:,1])+1))
for v in range(data.shape[0]):
    #horizontal:
    if data[v, 0, 0] == data[v, 1, 0]:
        start = data[v, 0, 1]
        end = data[v, 1, 1]
        x = data[v, 0, 0]
        if end < start:
            start, end = end, start
        for y in range(start, end+1):
            grid[x, y] += 1
        continue
    #vertical:
    if data[v, 0, 1] == data[v, 1, 1]:
        start = data[v, 0, 0]
        end = data[v, 1, 0]
        if end < start:
            start, end = end, start
        y = data[v, 0, 1]
        for x in range(start, end+1):
            grid[x, y] += 1
        continue
    #diagonal:
    n_steps = np.abs(data[v, 0, 0] - data[v, 1, 0])
    
    xs = np.linspace(data[v, 0, 0], data[v, 1, 0], n_steps+1, dtype=int)
    ys = np.linspace(data[v, 0, 1], data[v, 1, 1], n_steps+1, dtype=int)
    grid[xs, ys] += 1
    
print(grid.T)
print(np.sum(grid>1))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
21514
