In [11]:
import numpy as np
import re
import functools

with open("input.txt") as f:
    data = np.array([list(x) for x in f.read().split('\n')])

print(data)

[['.' '.' '>' ... 'v' '.' '>']
 ['v' 'v' 'v' ... 'v' '.' '.']
 ['.' '.' 'v' ... '.' '.' 'v']
 ...
 ['.' '.' '.' ... 'v' 'v' '.']
 ['v' 'v' '.' ... '.' '.' 'v']
 ['.' '.' '.' ... 'v' 'v' '.']]


In [12]:
def move(grid):
    leftroll = np.roll(grid,  1, axis=1)
    righroll = np.roll(grid, -1, axis=1)
    nxt = grid.copy()
    nxt[(grid == '.') & (leftroll == '>')] = '>'
    nxt[(grid == '>') & (righroll == '.')] = '.'
    downroll = np.roll(nxt,  1, axis=0)
    uppproll = np.roll(nxt, -1, axis=0)
    left = nxt.copy()
    nxt[(left == '.') & (downroll == 'v')] = 'v'
    nxt[(left == 'v') & (uppproll == '.')] = '.'
    return nxt, (nxt==grid).all()

step = 0
done = False
grid = data.copy()
while(not done):
    grid, done = move(grid)
    step += 1
print(step)




453


In [3]:
(11)%26

11

In [4]:
A = np.matrix("1 2 3 ; 4 5 6 ; 7 8 9")
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
np.roll(A, 1, axis=0)

matrix([[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]])

In [6]:
np.roll(A, -1, axis=0)

matrix([[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]])

In [7]:
np.roll(A, 1, axis=1)

matrix([[3, 1, 2],
        [6, 4, 5],
        [9, 7, 8]])

In [8]:
np.roll(A, -1, axis=1)

matrix([[2, 3, 1],
        [5, 6, 4],
        [8, 9, 7]])