In [7]:
import numpy as np
with open('input.txt') as f:
    data, folds = f.read().split('\n\n')
    data = np.array([x.split(',') for x in data.split('\n')], dtype=np.int64)
    folds = folds.split('\n')
for f in range(len(folds)):
    folds[f] = folds[f].split('=')
    folds[f][0] = folds[f][0][-1]
    folds[f][1] = int(folds[f][1])
    
grid = np.zeros((np.max(data[:,0])+1, np.max(data[:,1])+1))
for i in range(data.shape[0]):
    grid[data[i, 0],data[i,1]] = True
grid = grid.T
print(np.sum(grid))

820.0


In [2]:
def fold(grid, ori, c):
    if ori == 'y':
        newgrid = grid[:c,:] + grid[:c:-1,:]
    else:
        newgrid = grid[:, :c] + grid[:, :c:-1]
    return newgrid
fold1 = folds[0]

grid1 = fold(grid, fold1[0], fold1[1])
print(np.sum(grid1>0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
682


In [6]:
nxtfold = grid.copy()
for f in folds:
    nxtfold = fold(nxtfold, f[0], f[1])
for row in range(nxtfold.shape[0]):
    for col in range(nxtfold.shape[1]):
        print('#' if nxtfold[row, col] else '.',end='')
    print()


####..##...##..#..#.###..####.#..#.####.
#....#..#.#..#.#..#.#..#....#.#..#.#....
###..#..#.#....#..#.#..#...#..####.###..
#....####.#.##.#..#.###...#...#..#.#....
#....#..#.#..#.#..#.#.#..#....#..#.#....
#....#..#..###..##..#..#.####.#..#.####.
